package com.easybasic.board.dao;

import com.easybasic.board.model.Board;
import com.easybasic.eclassbrand.model.Activity;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface IBoardDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table board_board
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table board_board
     *
     * @mbggenerated
     */
    int insert(Board record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table board_board
     *
     * @mbggenerated
     */
    Board selectByPrimaryKey(Integer pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table board_board
     *
     * @mbggenerated
     */
    List<Board> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table board_board
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Board record);

    List<Board> selectListBySearch(@Param("searchStr") String searchStr, @Param("orderStr") String orderStr);
}
